#!/usr/bin/env bash
# Configure a new Ubuntu machine by installing Nginx, setting it to perform 301 redirection.

# Update package lists and install Nginx
echo -e "Updating and installing Nginx...\n"
sudo apt-get update -y -qq
sudo apt-get install nginx -y

# Start Nginx service
sudo service nginx start

# Allow Nginx on firewall(port 80)
sudo ufw allow 80/tcp

# Set ownership and permissions for website files
sudo chown -R "$USER":"$USER" /var/www/html && sudo chmod -R 755 /var/www

# Backup default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index with "Hello World!" content
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Modify Nginx configuration for 301 redirection using sed
sudo sed -i '/server {/a \       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

echo -e "\nNginx installation and configuration completed successfully."
