#!/usr/bin/env bash
# Configure a new Ubuntu machine by installing Nginx and setting it to listen on port 80.

# Update package lists and install Nginx
echo -e "Updating and installing Nginx...\n"
sudo apt-get update -y -qq
sudo apt-get install nginx -y

# Start Nginx service
sudo service nginx start

# Allow Nginx on firewall(port 80)
sudo ufw allow 80/tcp

# Set ownership and permissions for website files
sudo chown -R "$USER":"$USER" /var/www/html && sudo chmod -R 755 /var/www

# Backup default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index with "Hello World!" content
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Add content to your custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null

# Modify Nginx configuration to point to the custom 404 page
sudo sed -i '25i\       error_page 404 /error_404.html;\n\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default        

# Restart Nginx
sudo service nginx restart

echo -e "\nNginx installation and configuration completed successfully."
