#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 for all active IPv4 IPs

apt-get update
apt-get -y install curl
rm /etc/nginx/sites-available/*
rm /etc/nginx/sites-enabled/*~
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
