#!/usr/bin/env bash
# Bash script that loops from 1 to 10 printing various messages
loop_num=0
while [ $loop_num != 10 ]
do
   if [ $loop_num == 3 ]
   then
      echo "bad luck"
   elif [ $loop_num == 7 ]
   then
      echo "good luck"
   else
      echo "Best School"
   fi
   loop_num=$(( loop_num + 1 ))
done
