#!/usr/bin/env bash
# Configures Nginx to run as the nginx user and listen on port 8080.

chmod 644 /etc/nginx/nginx.conf

sed -i 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf

sed -i 's/listen       80;/listen       8080;/g' /etc/nginx/conf.d/default.conf

service nginx restart
